services:
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootmiconvoy
      MYSQL_DATABASE: miconvoy
      MYSQL_USER: miconvoy
      MYSQL_PASSWORD: miconvoy
    ports:
      - "3306:3306"
    volumes:
      - miconvoy_db_data:/var/lib/mysql

volumes:
  miconvoy_db_data:
