services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: miconvoy
      POSTGRES_PASSWORD: miconvoy
      POSTGRES_DB: miconvoy
    ports:
      - "5432:5432"
    volumes:
      - miconvoy_db_data:/var/lib/postgresql/data

volumes:
  miconvoy_db_data:
